### ISSUE TITLE
AlphaSmart Dana SDK missing.

### ISSUE THREAD

**Issue by JDat** [rtiangha/SiEd-Dana#3]
Where I can download AlphaSmart Dana SDK? Bad luck with google.

**Comment by livvy94** [comment]
I would also like to know this, all I found was someone in a flickr group who says you can DM him for the download, but probably hasn't logged on in forever since they never got back

**Comment by timtashpulatov** [comment]
Me too, want to update CyrHack II localization software to support AlphaSmart keyboard.

**Comment by livvy94** [comment]
Still hoping for some guidance on this

**Comment by rtiangha** [comment]
Sorry for the delay. I lost my dev environment when my laptop suffered a hard drive crash years ago and lost everything Palm OS related so unfortunately, I can't work on this project anymore. There might be something useful in the tools folder that may help you, but you're on your own to figure out the rest. Good luck!
